name: "PR Audit"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: 
      - main
      - "release/*"

jobs:
  semantics:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}